version: "3"
services:
    frontend:
        container_name: ds-frontend
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - ./.env-dev
        volumes:
            - ./docker_dir:/app/external
        ports:
            - 9001:80
