FROM node:10-alpine

WORKDIR /app

RUN apk --update add git curl nginx gettext && rm -rf /var/cache/apk/*
RUN npm install -g bower grunt-cli && \
    echo '{ "allow_root": true }' > /root/.bowerrc

ENV NGX_WORKERS 1
ENV NGX_SRVNAME _
ENV NGX_CONN 1024

COPY ./.docker_entrypoint_dev /usr/bin/entrypoint.sh
COPY ./.docker_nginx.conf /etc/nginx/nginx.conf.tmp

COPY ./ /app
RUN rm ./.docker*
RUN npm install
RUN bower install

RUN chmod a+x /usr/bin/entrypoint.sh

EXPOSE 80
EXPOSE 9001

ENTRYPOINT ["/usr/bin/entrypoint.sh"]

CMD ["grunt"]
