apiVersion: v1
kind: PersistentVolume
metadata:
  name: printworks-volume
  labels:
    type: local
spec:
  storageClassName: ""
  hostPath:
    path: "/var/www/app/data"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany